// IRC Defines 
const int WOL_NICKNAME_LEN= 9;

// Reply Defines 
// The following defines were taken from include/numeric.h 
// of the undernet-ircd distribution.
// See http://www.undernet.org/

//* reply's 
const int RPL_WELCOME         =   1;
const int RPL_YOURHOST     =      2;
const int RPL_CREATED      =      3;
const int RPL_MYINFO       =      4;
const int RPL_ISUPPORT     =      5;        // Undernet///dalnet extension 
const int RPL_BOUNCE      = 0;                  // IRCnet extension 
const int RPL_MAP		  =     6;	//unreal 
const int RPL_MAPEND	      =      7;	//unreal 
const int RPL_SNOMASK      =      8;        // Undernet extension 
const int RPL_STATMEMTOT   =      9;        // Undernet extension 
const int RPL_STATMEM      =     10;        // Undernet extension 
const int RPL_YOURCOOKIE   =     14;       //    IRCnet extension 
const int RPL_MAPMORE    =       16;        // Undernet extension 
const int RPL_YOURID	    =  42;	//IRCnet extension 
const int RPL_ATTEMPTINGJUNC   = 50;           //aircd extension 
const int RPL_ATTEMPTINGREROUTE = 51;           //aircd extension 
//Numberic replies from server commands.
//These are currently in the range 200-399.
const int RPL_TRACELINK    =    200;
const int RPL_TRACECONNECTING = 201;
const int RPL_TRACEHANDSHAKE  = 202;
const int RPL_TRACEUNKNOWN   =  203;
const int RPL_TRACEOPERATOR  =  204;
const int RPL_TRACEUSER      =  205;
const int RPL_TRACESERVER   =   206;
const int RPL_TRACENEWTYPE  =   208;
const int RPL_TRACECLASS    =   209;
const int RPL_STATS        =    210; //aircd extension, used instead of having //       multiple stats numerics 
const int RPL_TRACERECONNECT  = 210; //IRCnet extension                                  
const int RPL_STATSLINKINFO  =  211;
const int RPL_STATSCOMMANDS  =  212;
const int RPL_STATSCLINE     =  213;
const int RPL_STATSOLDNLINE  =  214;   //unreal 
const int RPL_STATSNLINE     =  214; // unused 
const int RPL_STATSILINE    =   215;
const int RPL_STATSKLINE   =    216;
const int RPL_STATSPLINE   =    217;        // Undernet extenstion 
const int RPL_STATSQLINE    =   217;          // Various 
const int RPL_STATSYLINE   =    218;
const int RPL_ENDOFSTATS   =    219;        // See also RPL_STATSDLINE 
const int RPL_STATSBLINE   =    220;	 //  Numerics List: //dalnet,unreal 
const int RPL_UMODEIS      =    221;
const int RPL_SQLINE_NICK	=     222;	 //  Numerics List: //dalnet 
const int RPL_STATSELINE   =    223;	   //dalnet 
const int RPL_STATSFLINE   =    224;      //    Hybrid extension,//dalnet 
const int RPL_STATSTLINE	  =   224;	   //unreal 
const int RPL_STATSDLINE    =   225;         // Hybrid extension 
const int RPL_STATSZLINE	  =   225;	   //dalnet
const int RPL_STATSCOUNT	  =   226;	   //dalnet
const int RPL_STATSVLINE	 =    227;	 //  unreal 
const int RPL_SERVICEINFO    =  231;	// unused 
const int RPL_ENDOFSERVICES  =  232;	// unused 
const int RPL_RULES	   =  232;	//unreal 
const int RPL_SERVICE    =      233;	// unused 
const int RPL_SERVLIST      =   234;	// unused 
const int RPL_SERVLISTEND   =   235;	// unused 
const int RPL_STATSENGINE  =    237;	// Undernet engine name 
const int RPL_STATSIAUTH   =    239;        //   IRCnet extension 
const int RPL_STATSLLINE   =    241;	
const int RPL_STATSUPTIME  =    242;
const int RPL_STATSOLINE   =    243;
const int RPL_STATSHLINE   =    244;
const int RPL_STATSSLINE   =    245;       //    Reserved / //dalnet / IRCnet / EFnet 
const int RPL_STATSSPING	  =   246;	   //Numerics List: IRCnet 
const int RPL_STATSULINE	  =   246;	//dalnet 
const int RPL_STATSGLINE    =   247;        // Undernet extension 
const int RPL_STATSXLINE    =   247;       //    hybrid extension,PTlink,unreal 
const int RPL_STATSDEFINE	=     248;	//   Numerics List: IRCnet 
const int RPL_STATSDEBUG   =    249;        // Extension to RFC1459 
const int RPL_STATSCONN    =    250;        // Undernet extension 
const int RPL_LUSERCLIENT  =    251;
const int RPL_LUSEROP      =    252;
const int RPL_LUSERUNKNOWN  =   253;
const int RPL_LUSERCHANNELS =   254;
const int RPL_LUSERME       =   255;
const int RPL_ADMINME      =    256;
const int RPL_ADMINLOC1    =    257;
const int RPL_ADMINLOC2    =    258;
const int RPL_ADMINEMAIL   =    259;
const int RPL_TRACELOG     =    261;	// unused 
const int RPL_TRACEPING    =    262;        // Extension to RFC1459, unused 
const int RPL_TRACEEND	  =   262;	   //efnet(?) Numerics List: IRCnet 
const int RPL_LOAD_THROTTLED  = 263;      //    efnet/hybrid 
const int RPL_TRYAGAIN	  =   263;	   //Numerics List: IRCnet 
const int RPL_LOAD2HI	  =   263;	   //dalnet 
const int RPL_CURRENT_LOCAL  =  265;           //aircd/efnet/hybrid///dalnet
const int RPL_CURRENT_GLOBAL =  266;           //aircd/efnet/hybrid///dalnet 
const int RPL_START_NETSTAT =   267;           //aircd 
const int RPL_NETSTAT      =    268;           //aircd 
const int RPL_END_NETSTAT  =    269;          // aircd 
const int RPL_PRIVS         =   270;	// Undernet extension - privs 
const int RPL_SILELIST     =    271;        // Undernet extension 
const int RPL_ENDOFSILELIST =   272;        // Undernet extension 
const int RPL_NOTIFY       =    273;      //    aircd 
const int RPL_END_NOTIFY   =    274;        //   aircd 
const int RPL_STATSDELTA    =   274;         //  IRCnet extension 
const int RPL_GLIST        =    280;        // Undernet extension 
const int RPL_ENDOFGLIST   =    281;        // Undernet extension 
const int RPL_JUPELIST      =   282;        // Undernet extension - jupe -Kev 
const int RPL_ENDOFJUPELIST =   283;        // Undernet extension - jupe -Kev 
const int RPL_FEATURE	=     284;	// Undernet extension - features 
const int RPL_CHANINFO_HANDLE = 285;         //  aircd 
const int RPL_CHANINFO_USERS  = 286;        //   aircd 
const int RPL_CHANINFO_CHOPS  = 287;       //    aircd 
const int RPL_CHANINFO_VOICES = 288;      //     aircd 
const int RPL_CHANINFO_AWAY  =  289;     //      aircd 
const int RPL_CHANINFO_OPERS  = 290;    //       aircd 
const int RPL_HELPHDR	 =    290;	//Numeric List: //dalnet 
const int RPL_CHANINFO_BANNED = 291;    //       aircd 
const int RPL_HELPOP	  =   291;	//Numeric List: //dalnet 
const int RPL_CHANINFO_BANS  =  292;     //      aircd 
const int RPL_HELPTLR	  =   292;	//Numeric List: //dalnet 
const int RPL_CHANINFO_INVITE = 293;    //       aircd 
const int RPL_HELPHLP	 =    293;	//Numeric List: //dalnet 
const int RPL_CHANINFO_INVITES = 294;    //       aircd 
const int RPL_HELPFWD	   =  294;	//Numeric List: //dalnet 
const int RPL_CHANINFO_KICK =   295;       //    aircd 
const int RPL_HELPIGN	  =   295;	//Numeric List: //dalnet 
const int RPL_CHANINFO_KICKS  = 296;      //     aircd 
const int RPL_END_CHANINFO  =   299;     //      aircd 
const int RPL_NONE      =       300;	// unused 
const int RPL_AWAY       =      301;
const int RPL_USERHOST    =     302;
const int RPL_ISON       =      303;
const int RPL_TEXT       =      304; 	// unused 
const int RPL_UNAWAY     =      305;
const int RPL_NOWAWAY    =      306;
const int RPL_USERIP     =      307;        // Undernet extension  // NotAway, aircd 
const int RPL_WHOISREGNICK  =   307; 	//Numeric List: //dalnet 
const int RPL_SUSERHOST	   =  307;	//austnet 
const int RPL_NOTIFYACTION =    308;    //     aircd 
const int RPL_WHOISADMIN	   =  308;	//Numeric List: //dalnet 
const int RPL_RULESSTART	   =  308;	//unreal 
const int RPL_NICKTRACE    =    309;        // aircd 
const int RPL_WHOISSADMIN	=     309;	//Numeric List: //dalnet 
const int RPL_ENDOFRULES	  =   309;	//unreal 
const int RPL_WHOISHELPER	=     309;	//austnet 
const int RPL_WHOISSVCMSG   =   310;         //dalnet 
const int RPL_WHOISHELPOP	=     310;	//unreal 
const int RPL_WHOISSERVICE  =   310;	//austnet 
const int RPL_WHOISUSER     =   311;        // See also RPL_ENDOFWHOIS 
const int RPL_WHOISSERVER    =  312;
const int RPL_WHOISOPERATOR  =  313;
const int RPL_WHOWASUSER     =  314;        // See also RPL_ENDOFWHOWAS 
const int RPL_ENDOFWHO       =  315;        // See RPL_WHOREPLY/RPL_WHOSPCRPL 
const int RPL_WHOISCHANOP   =   316;         //  removed from RFC1459 
const int RPL_WHOISIDLE     =   317;
const int RPL_WHOISCHANNELS =   319;
const int RPL_WHOIS_HIDDEN   =  320;    //    Anothernet +h, ick! 
const int RPL_WHOISSPECIAL   =  320;	//unreal 
const int RPL_LISTSTART      =  321;
const int RPL_LIST           =  322;
const int RPL_LISTEND        =  323;
const int RPL_CHANNELMODEIS  =  324;
const int RPL_CHANNELPASSIS  =  325;          // IRCnet extension 
const int RPL_UNIQOPIS       =  325;          // IRCnet extension 
const int RPL_NOCHANPASS     =  326;         //  IRCnet extension 
const int RPL_CHPASSUNKNOWN  =  327;        //   IRCnet extension 
const int RPL_CHANNEL_URL    =  328;       //    //dalnet, anothernet 
const int RPL_CREATIONTIME   =  329;
const int RPL_WHOWAS_TIME    =  330;              
const int RPL_NOTOPIC        =  331;
const int RPL_TOPIC          =  332;
const int RPL_TOPICWHOTIME   =  333;        // Undernet extension 
const int RPL_LISTUSAGE      =  334;        // Undernet extension 
const int RPL_COMMANDSYNTAX  =  334;	   //dalnet 
const int RPL_LISTSYNTAX	    = 334;	   //unreal 
const int RPL_CHANPASSOK     =  338;           //IRCnet extension (?)
const int RPL_WHOISACTUALLY  =  338;	   //dalnet
const int RPL_BADCHANPASS    =  339;          // IRCnet extension (?)
const int RPL_INVITING   =      341;
const int RPL_SUMMONING  =      342;         //  removed from RFC1459 
const int RPL_INVITELIST      = 346;        // IRCnet, Undernet extension 
const int RPL_ENDOFINVITELIST = 347;        // IRCnet, Undernet extension 
const int RPL_EXCEPTLIST      = 348;   
const int RPL_ENDOFEXCEPTLIST = 349;     
const int RPL_VERSION         = 351;
const int RPL_WHOREPLY        = 352;       // See also RPL_ENDOFWHO 
const int RPL_NAMREPLY        = 353;       // See also RPL_ENDOFNAMES 
const int RPL_WHOSPCRPL       = 354;       // Undernet extension,
const int RPL_KILLDONE        = 361;	// Not used
const int RPL_CLOSING         = 362;
const int RPL_CLOSEEND        = 363;
const int RPL_LINKS           = 364;
const int RPL_ENDOFLINKS      = 365;
const int RPL_ENDOFNAMES      = 366;       // See RPL_NAMREPLY 
const int RPL_BANLIST         = 367;
const int RPL_ENDOFBANLIST    = 368;
const int RPL_ENDOFWHOWAS     = 369;
const int RPL_INFO            = 371;
const int RPL_MOTD            = 372;
const int RPL_INFOSTART       = 373;// not used 
const int RPL_ENDOFINFO       = 374;
const int RPL_MOTDSTART       = 375;
const int RPL_ENDOFMOTD       = 376;
const int RPL_KICKEXPIRED =     377;   //aircd 
const int RPL_SPAM	    = 377;   //austnet 
const int RPL_BANEXPIRED  =     378;  //aircd 
const int RPL_KICKLINKED  =     379;  //aircd 
const int RPL_BANLINKED   =     380;   //aircd 
const int RPL_YOUREOPER    =    381;
const int RPL_REHASHING    =    382;
const int RPL_YOURSERVICE	=     383;	  // Numeric List: various 
const int RPL_MYPORTIS      =   384;	// not used 
const int RPL_NOTOPERANYMORE =  385;       // Extension to RFC1459, not used 
const int RPL_QLIST	   =  386;	//unreal 
const int RPL_ENDOFQLIST	=     387;	//unreal 
const int RPL_ALIST	   =  388;	//unreal 
const int RPL_ENDOFALIST	 =    389;	//unreal  
const int RPL_TIME        =     391;
const int RPL_START_USERS  =    392;        //dalnet/EFnet/IRCnet 
const int RPL_USERS         =   393;        //dalnet/EFnet/IRCnet 
const int RPL_END_USERS     =   394;        //dalnet/EFnet/IRCnet 
const int RPL_NOUSERS       =   395;        //dalnet/EFnet/IRCnet 
const int RPL_INSIDER       = 399;
//
// * Numberic replies from server commands.
// * These are currently in the range 600-699.
const int RPL_LOGON		=	 600;		   //dalnet,unreal
const int RPL_LOGOFF      =     601;		   //dalnet,unreal
const int RPL_WATCHOFF    =     602;		   //dalnet,unreal
const int RPL_WATCHSTAT   =     603;		   //dalnet,unreal
const int RPL_NOWON       =     604;		   //dalnet,unreal
const int RPL_NOWOFF      =     605;		   //dalnet,unreal
const int RPL_WATCHLIST   =     606;		   //dalnet,unreal
const int RPL_ENDOFWATCHLIST =  607;		   //dalnet,unreal
const int RPL_DCCSTATUS     =   617;		   //dalnet
const int RPL_DCCLIST        =  618;		   //dalnet
const int RPL_ENDOFDCCLIST   =  619;		   //dalnet
const int RPL_DCCINFO        =  620;		   //dalnet
const int RPL_DUMPING		=	 640;		 //  unreal
const int RPL_DUMPRPL	=		 641;		//   unreal
const int RPL_EODUMP		=	 642;		   //unreal
//
// Westwood Online Extensions
//
const int RPL_GAME_CHANNEL  =   326;
const int RPL_CHANNEL	=		 327;
const int RPL_GET_CODEPAGE   =  328;	
const int RPL_SET_CODEPAGE  =   329;
const int RPL_GET_LOCALE	   =  309;
const int RPL_SET_LOCALE	   =  310;
const int RPL_BATTLECLAN	  =   358;
const int RPL_BAD_LOGIN      =  378;
const int RPL_VERCHK_NONREQ  =  379;  // for WOL 
const int RPL_FIND_USER_EX    = 398;
const int RPL_UPDATE_RECORD =   602;
const int RPL_IRCSERV		=	 605;
const int RPL_ENDSERVLIST	=     607;
const int RPL_GAMERESSERV	=     608;
const int RPL_LADDERSERV	 =    609;
const int RPL_LOBCOUNT	 =    610;
const int ERR_IDNOEXIST     =   439;
const int ERR_GAMECHANCLOSED =  478;
//* error's 
//* Errors are in the range from 400-599 currently and are grouped by what
//* commands they come from.
//
const int ERR_FIRSTERROR    =   400;	// unused 
const int ERR_NOSUCHNICK    =   401;
const int ERR_NOSUCHSERVER  =   402;
const int ERR_NOSUCHCHANNEL  =  403;
const int ERR_CANNOTSENDTOCHAN = 404;
const int ERR_TOOMANYCHANNELS =  405;
const int ERR_WASNOSUCHNICK  =  406;
const int ERR_TOOMANYTARGETS =  407;
const int ERR_NOSUCHSERVICE  =  408;  //IRCnet 
const int ERR_NOCOLORSONCHAN =  408;  //dalnet 
const int ERR_NOORIGIN       =  409;
const int ERR_NORECIPIENT    =  411;
const int ERR_NOTEXTTOSEND   =  412;
const int ERR_NOTOPLEVEL     =  413;
const int ERR_WILDTOPLEVEL   =  414;
const int ERR_BADMASK        =  415;           //IRCnet extension 
const int ERR_QUERYTOOLONG   =  416;        // Undernet extension 
const int ERR_TOOMANYMATCHES =  416;          //IRCnet extension 
const int ERR_LENGTHTRUNCATED = 419;        //  aircd 
const int ERR_UNKNOWNCOMMAND =  421;
const int ERR_NOMOTD        =   422;
const int ERR_NOADMININFO   =   423;
const int ERR_FILEERROR     =   424;       //   removed from RFC1459 
const int ERR_TOOMANYAWAY	 =    429;	    //dalnet 
const int ERR_NONICKNAMEGIVEN = 431;
const int ERR_ERRONEUSNICKNAME = 432;
const int ERR_NICKNAMEINUSE  =  433;
const int ERR_SERVICENAMEINUSE = 434; //unreal
const int ERR_NORULES	 =    434;   //unreal 
const int ERR_SERVICECONFUSED = 435; //unreal
const int ERR_BANONCHAN	   =  435;   //dalnet 
const int ERR_NICKCOLLISION  =  436;
const int ERR_BANNICKCHANGE  =  437;        // Undernet extension 
const int ERR_UNAVAILRESOURCE = 437;           //IRCnet extension 
const int ERR_NICKTOOFAST    =  438;        // Undernet extension 
const int ERR_DEAD           =  438;           //IRCnet reserved for later use 
const int ERR_TARGETTOOFAST  =  439;        // Undernet extension 
const int ERR_SERVICESDOWN    = 440;	//dalnet,unreal 
const int ERR_USERNOTINCHANNEL = 441;
const int ERR_NOTONCHANNEL  =   442;
const int ERR_USERONCHANNEL =   443;
const int ERR_NOLOGIN       =   444;     //     removed from RFC1459 
const int ERR_SUMMONDISABLED =  445;     //      removed from RFC1459 
const int ERR_USERSDISABLED  =  446;    //       removed from RFC1459 
const int ERR_NONICKCHANGE   =  447;	// unreal 
const int ERR_NOTREGISTERED   = 451;
const int ERR_IDCOLLISION    =  452;         //  IRCnet extension ? 
const int ERR_NICKLOST      =   453;        //   IRCnet extension ? 
const int ERR_HOSTILENAME	 =    455;	//   unreal 
const int ERR_NOHIDING	   =  459;	  // unreal 
const int ERR_NOTFORHALFOPS =   460;	 //  unreal 
const int ERR_NEEDMOREPARAMS  = 461;
const int ERR_ALREADYREGISTRED = 462;
const int ERR_NOPERMFORHOST  =  463;
const int ERR_PASSWDMISMATCH  = 464;
const int ERR_YOUREBANNEDCREEP = 465;
const int ERR_YOUWILLBEBANNED = 466;
const int ERR_KEYSET         =  467;       // // Undernet extension 
const int ERR_INVALIDUSERNAME = 468;       // // Undernet extension 
const int ERR_ONLYSERVERSCANCHANGE = 468;	//   //dalnet,unreal 
const int ERR_LINKSET	   =  469;	    //unreal 
const int ERR_LINKCHANNEL	=     470;	//unreal 
const int ERR_KICKEDFROMCHAN  = 470;      //aircd 
const int ERR_CHANNELISFULL  =  471;
const int ERR_UNKNOWNMODE    =  472;
const int ERR_INVITEONLYCHAN =  473;
const int ERR_BANNEDFROMCHAN =  474;
const int ERR_BADCHANNELKEY  =  475;
const int ERR_BADCHANMASK    =  476;        //// Undernet extension 
const int ERR_NEEDREGGEDNICK =  477;        ////dalnet Extention 
const int ERR_BANLISTFULL    =  478;        //// Undernet extension 
const int ERR_LINKFAIL	   =  479;	     //unreal 
const int ERR_BADCHANNAME   =   479;        //// EFNet extension  //// 479 Undernet extension badchan 
const int ERR_CANNOTKNOCK	=     480;	 //unreal 
const int ERR_NOULINE	   =  480;	     //austnet 
const int ERR_NOPRIVILEGES   =  481;
const int ERR_CHANOPRIVSNEEDED = 482;
const int ERR_CANTKILLSERVER =  483;
const int ERR_ISCHANSERVICE  =  484;        //// Undernet extension 
const int ERR_DESYNC	  =   484;	         ////dalnet,PTlink 
const int ERR_ATTACKDENY	  =   484;	     //unreal 
const int ERR_RESTRICTED	   =  484;	     //// IRCnet extension 
const int ERR_UNIQOPRIVSNEEDED =  485;       //IRCnet extension 
const int ERR_KILLDENY       =  485;	     //unreal 
const int ERR_CANTKICKADMIN  =  485;	     //PTlink 
const int ERR_HTMDISABLED    =  486;	     //unreal 
const int ERR_CHANTOORECENT =   487;        //IRCnet extension (?) 
const int ERR_TSLESSCHAN    =   488;        //IRCnet extension (?) 
const int ERR_VOICENEEDED   =   489;        //// Undernet extension 
const int ERR_NOOPERHOST     =  491;
const int ERR_NOSERVICEHOST  =  492; 	     //IRCnet extension 
const int ERR_NOFEATURE	   =  493;	     //// Undernet extension - features 
const int ERR_BADFEATVALUE  =   494;        //// Undernet extension - features 
const int ERR_BADLOGTYPE	   =  495;	     //// Undernet extension - features 
const int ERR_BADLOGSYS	   =  496;	     //// Undernet extension - features 
const int ERR_BADLOGVALUE	=     497;	 //// Undernet extension - features 
const int ERR_ISOPERLCHAN   =   498;      //// Undernet extension 
const int ERR_UMODEUNKNOWNFLAG = 501;
const int ERR_USERSDONTMATCH =  502;
const int ERR_GHOSTEDCLIENT =   503;         //  efnet 
const int ERR_VWORLDWARN	   =  503;	   //austnet 
const int ERR_SILELISTFULL   =  511;        // Undernet extension 
const int ERR_NOTIFYFULL     =  512;           //aircd 
const int ERR_TOOMANYWATCH  =   512;          // Numeric List: //dalnet 
const int ERR_NOSUCHGLINE   =   512;        // Undernet extension 
const int ERR_BADPING       =   513;        // Undernet extension 
const int ERR_NEEDPONG	   =  512;         //Numeric List: //dalnet 
const int ERR_NOSUCHJUPE   =    514;        // Undernet extension - jupe -Kev 
const int ERR_TOOMANYDCC	  =   514;	//dalnet 
const int ERR_BADEXPIRE    =    515;   // Undernet extension - jupe -Kev 
const int ERR_DONTCHEAT	  =   516;	// Undernet extension 
const int ERR_DISABLED	  =   517;	// Undernet extension -Kev 
const int ERR_NOINVITE	 =    518;	//unreal 
const int ERR_LONGMASK	  =   518;	// Undernet extension -Kev 
const int ERR_ADMONLY	   =  519;	//unreal 
const int ERR_TOOMANYUSERS  =   519;	// Undernet extension -Kev 
const int ERR_OPERONLY	  =   520;	//unreal 
const int ERR_MASKTOOWIDE	=     520;	// Undernet extension -Kev 
const int ERR_WHOTRUNC	  =   520;	//austnet 
const int ERR_LASTERROR     =   521;
const int ERR_LISTSYNTAX   =    521;	//dalnet
const int ERR_WHOSYNTAX	  =   522;        //dalnet
const int ERR_WHOLIMEXCEED =    523;	//dalnet 